version: "2"
services:
  membersrvc:
    build:
      context: "./membersrvc"
    command: membersrvc
    container_name : docker_membersrvc
    ports:
      - "7054:7054"
  e-logcard-application:
    image: mongo:latest
    #container_name : docker_vp1
    ports:
      - "27017:27017"
  vp0:
    image: hyperledger/fabric-peer:latest
    command: "sh -c 'while ! nc membersrvc 7054; do sleep 1; done; peer node start'"
    container_name : docker_vp0
    environment:
      # ADJUST PEER DISCOVERY 
      - CORE_PEER_DISCOVERY_PERIOD=60s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=61s
      - CORE_PEER_ADDRESSAUTODETECT=true
      # PEER CONFIGURATION
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=vp0
      - CORE_SECURITY_ENROLLID=test_vp0
      - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
      # PEER SECURITY
      - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
      - CORE_SECURITY_ENABLED=true
      # IF PBFT CONSENSUS
      #- CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft 
      #- CORE_PBFT_GENERAL_MODE=batch 
      #- CORE_PBFT_GENERAL_N=4 
    links:
      - membersrvc
    ports:
      - "7050:7050"
      - "7051:7051"
      - "7052:7052"
      - "7053:7053"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"